BerkeleyHCI/edg-ide

- src/main/scala/edg_ide/swing/CompilerErrorTreeTableModel.scala
- src/main/scala/edg_ide/ui/EdgCompilerService.scala
- src/main/scala/edg_ide/ui/KicadVizPanel.scala
Consistency updates for BerkeleyHCI/PolymorphicBlocks#92
> Single-shot generator refactor

- build.sbt
- developing.md
- project/plugins.sbt
- src/main/scala/edg_ide/Icons.scala
- src/main/scala/edg_ide/actions/SetVisualizerTopAction.scala
- src/main/scala/edg_ide/ui/LibraryPanel.scala
- src/main/scala/edg_ide/util/DesignAnalysisUtils.scala
Zero deprecations, yay!
And no more Java versioning issues!
> Update IntelliJ version and remove deprecations

- src/main/scala/edg_ide/ui/EdgCompilerService.scala
just one simple change it turns out
> Fix IndexNotReady error

- src/main/scala/edg_ide/runner/CompileProcessHandler.scala
- src/main/scala/edg_ide/ui/BlockVisualizerPanel.scala
- src/main/scala/edg_ide/ui/EdgCompilerService.scala
Also actually update discarded status on visualizer
> Move cache discard UI to run console

- src/main/scala/edg_ide/runner/CompileProcessHandler.scala
- src/main/scala/edg_ide/runner/DesignTopRunConfigurationType.scala
- src/main/scala/edg_ide/ui/EdgCompilerService.scala
- src/main/scala/edg_ide/util/ExceptionNotify.scala
Mostly moving code around to clean things up
> Refactor debugging information

- src/main/scala/edg_ide/runner/CompileProcessHandler.scala
- src/main/scala/edg_ide/runner/DseProcessHandler.scala
- src/main/scala/edg_ide/swing/CompilerErrorTreeTableModel.scala
- Error checks as separate transforms
- Updated CompilerErorr and ElaborateRecord cases
> Update for latest HDL compiler changes

- src/main/scala/edg_ide/dse/DseConfigElement.scala
- src/main/scala/edg_ide/runner/DseProcessHandler.scala
- src/main/scala/edg_ide/ui/BlockVisualizerPanel.scala
As the title implies, makes DSE more efficient.
Also discards conflicting user-specified refinements, but logs a warning.
Note: DSE is still an experimental feature that is gated behind a feature flag.
> Use compiler forking for design space exploration

- src/main/scala/edg_ide/EdgirUtils.scala
- src/main/scala/edg_ide/actions/FocusToElementAction.scala
- src/main/scala/edg_ide/edgir_graph/EdgirGraph.scala
- src/main/scala/edg_ide/psi_edits/InsertPinningAction.scala
- src/main/scala/edg_ide/runner/DseProcessHandler.scala
- src/main/scala/edg_ide/swing/BlockTreeTableModel.scala
- src/main/scala/edg_ide/swing/ElementDetailTreeModel.scala
- src/main/scala/edg_ide/ui/ConnectTool.scala
- src/main/scala/edg_ide/ui/DesignFastPathUtil.scala
- src/main/scala/edg_ide/ui/LibraryPanel.scala
- src/main/scala/edg_ide/util/DesignFindDisconnected.scala
- src/test/scala/edg_ide/edgir_graph/tests/EdgirGraphTest.scala
- src/test/scala/edg_ide/util/tests/DesignFindBlockOfTypesTest.scala
- src/test/scala/edg_ide/util/tests/DesignFindDisconnectedTest.scala
IDE changes for BerkeleyHCI/PolymorphicBlocks#175
> Order map elements in proto

- src/main/scala/edg_ide/runner/CompileProcessHandler.scala
Update for BerkeleyHCI/PolymorphicBlocks#178, invokes refdeser as part of the compilation process
> Separate refdesing pass

- src/main/scala/edg_ide/swing/CompilerErrorTreeTableModel.scala
... which changed the connect data structure
> Update HDL submodule for directed assigns

- src/main/scala/edg_ide/dse/DseResult.scala
- src/main/scala/edg_ide/runner/DseProcessHandler.scala
- src/main/scala/edg_ide/runner/DseRunConfigurationType.scala
- src/main/scala/edg_ide/swing/dse/DseConfigTreeTableModel.scala
- src/main/scala/edg_ide/swing/dse/DseResultTreeTableModel.scala
- src/main/scala/edg_ide/swing/dse/JScatterPlot.scala
- src/main/scala/edg_ide/ui/BlockVisualizerPanel.scala
- src/main/scala/edg_ide/ui/BlockVisualizerService.scala
- src/main/scala/edg_ide/ui/DetailPanel.scala
- src/main/scala/edg_ide/ui/DsePanel.scala
- src/main/scala/edg_ide/ui/tools/DefaultTool.scala
- src/main/scala/edg_ide/util/ExceptionNotify.scala
_DSE is an experimental feature and not enabled by default._
Various small UI improvements
- Remove user-specified objective name - which simplifies a lot of other logic
- Improvements to plot
- Yellow highlight on hover, distinct from larger circle when selected
- Move axis line to data origin
- Hide axis lines for ordinals
- Auto-hide/show DSE panel based on selected run config
- Show text entry when creating DSE config
> DSE UI Improvements

- src/main/scala/edg_ide/psi_edits/InsertRefinementAction.scala
- src/main/scala/edg_ide/ui/DetailPanel.scala
Add GUI action to insert refinement from a value selected in the detail panel.
Also acts as a inexpensive way to copy a value as text, by turning it into code.
> Insert refinement from value

- src/main/scala/edg_ide/swing/FootprintBrowserTreeTableModel.scala
> Don't error out on null directory.list()

- src/main/scala/edg_ide/swing/CompilerErrorTreeTableModel.scala
- src/main/scala/edg_ide/ui/BlockVisualizerPanel.scala
Added new CustomTableHeader class that supports a popup tooltip when mouse hovers over it. 
Used it in error panel table.
> Path info popup

- src/main/scala/edg_ide/runner/CompileProcessHandler.scala
- src/main/scala/edg_ide/runner/DseProcessHandler.scala
- src/main/scala/edg_ide/swing/ColorUtil.scala
- src/main/scala/edg_ide/swing/dse/DseResultTreeTableModel.scala
- src/main/scala/edg_ide/swing/dse/JDsePlot.scala
- src/main/scala/edg_ide/swing/dse/JParallelCoordinatesPlot.scala
- src/main/scala/edg_ide/swing/dse/JScatterPlot.scala
- src/main/scala/edg_ide/swing/dse/PlotAxis.scala
- src/main/scala/edg_ide/ui/dse/DseParallelPlotPanel.scala
- src/main/scala/edg_ide/ui/dse/DseScatterPlotPanel.scala
- src/main/scala/edg_ide/util/DesignAnalysisUtils.scala
Misc improvements
- Progress bar shows status while compiling, especially for DSE
- DSE results table: don't nest single result set
- DSE: for subclass refinement, sort the default refinement as the first element
- DSE: add z-ordering for points (so error and ideal points deprioritized)
- DSE: support area select by dragging, panning moved to middle mouse
- DSE: color tuning, tbh still not amazing
> UI Improvement

- src/main/scala/edg_ide/swing/dse/JDsePlot.scala
Change select UI parameters, update submodule
> UI tweaking

- src/main/scala/edg_ide/dse/DseConfigElement.scala
- src/main/scala/edg_ide/dse/DseResult.scala
- src/main/scala/edg_ide/swing/ElementDetailTreeModel.scala
- src/main/scala/edg_ide/ui/ParamToUnitsStringUtil.scala
- src/main/scala/edg_ide/util/SiPrefixUtil.scala
- src/test/scala/edg_ide/dse/tests/DsePathParameterSearchTest.scala
in DSE config display and parsing (user text editing)
> Support SI prefixes and center-tolerance format in more places

- src/main/scala/edg_ide/swing/RefinementsNodes.scala
Roll the submodule and add the new case to the refinement display tree view
> Update for new directed refinements HDL feature

- src/main/scala/edg_ide/swing/CompilerErrorTreeTableModel.scala
> Update HDL submodule

- src/main/scala/edg_ide/runner/CompileProcessHandler.scala
- src/main/scala/edg_ide/runner/DseProcessHandler.scala
- Update to be compatible when the HDL is installed from a pip package, instead of editing the HDL repo directly.
> Python packaging compatibility

- src/main/scala/edg_ide/runner/CompileProcessHandler.scala
- src/main/scala/edg_ide/runner/DseProcessHandler.scala
- src/main/scala/edg_ide/ui/BlockVisualizerPanel.scala
> Add Done to build console, fix a NPE

- src/main/scala/edg_ide/swing/blocks/JBlockDiagramVisualizer.scala
- src/main/scala/edg_ide/ui/BlockVisualizerPanel.scala
These ports appear dimmed out and cannot be selected or mouseover-highlighted, but will display a tooltip.
Infrastructure: add an unselectable node set to the block diagram visualizer with the above behavior. A refinement-only-paths DesignMap reads in the refinement-only metadata generated by the compiler and translates it to the unselectable node set.
> Make post-refinement-only ports non-interactable in block diagram visualizer

- src/main/scala/edg_ide/psi_edits/InsertionLiveTemplate.scala
So on the template start it shows up at the beginning of the template marker (instead of first variable) - especially useful for templates with no arguments where the tooltip shows up at the end.
> Fix tooltip for insertion live template

- src/main/scala/edg_ide/runner/CompileProcessHandler.scala
- src/main/scala/edg_ide/runner/DseProcessHandler.scala
Also updates the base HDL submodule pointer, and style cleanup.
Resolves #119
> Check HDL version

- src/main/scala/edg_ide/swing/blocks/ElkNodePainter.scala
... by fixing the modifier application ordering
> Fix block diagram select underlay

- build.sbt
- project/build.properties
> Bump to Scala 2.13.14, sbt 1.9.9 

- src/main/scala/edg_ide/psi_edits/InsertRefinementAction.scala
- src/main/scala/edg_ide/swing/CompilerErrorTreeTableModel.scala
including the massive performance bug fix, and some interface changes from it
> Bump version of hdl submodule
